spring:
  profiles:
    active: test   



---     
spring:
    profiles: test
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ecommerce_yuki_sawamura
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
server:
  context-path: /ecommerce-springC-sawamura
  port: 8081

---     
spring:
    profiles: dev
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://172.16.0.17:5432/ecommerce_yuki_sawamura
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp


server:
  context-path: /ecommerce-springC-sawamura
  port: 8081
  
